spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
app.admin.email=${APP_ADMIN_EMAIL}
app.admin.senha=${APP_ADMIN_SENHA}