spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=david
app.admin.email=${APP_ADMIN_EMAIL:superadmin@cognisys.com}
app.admin.senha=${APP_ADMIN_SENHA:cognisys}